apiVersion: v1
kind: Pod
metadata:
  name: myweb  # pod 的名字
  labels:
    name: myweb
spec:
  containers:
    - name: myweb
      image: kubeguide/tomcat-app:v1
        # resources:
        # limits: # 该资源的最大允许使用的量
        # memory: "128Mi"
      # cpu: "500m"
      ports:
        - containerPort: 8888
      env:
        - name: MYSQL_SERVICE_HOST
          value :'mysql'
        - name: MYSQL_SERVICE_PORT
          value: '3306'


      # pod 的ip加上这里的容器端口containerPort，就组成一个新的概念--Endpoint
      # 代表着此pod里的一个服务进程的对外通信地址。

      # Event是一个事件的记录，记录了事件的 的众多信息
      # 通常会管理到某个具体的资源对象上
