apiVersion: v1
kind: Pod  # 表明是一个pod
metadata:
  name: myweb
  labels:
    name: myweb
spec:
  containers:
    - name: myweb
      image: kubeguide/tomcat-app:v1
      # resources:
      #   limits:
      #     memory: "128Mi"
      #     cpu: "500m"
      ports:   # pod的ip 加上容器端口，就组成了Endpoint，代表此pod里的一个服务进程对外通信地址
        - containerPort: 8080
      env:
        - name: MYSQL_SERVICE_HOST
          value: 'mysql'
        - name: MYSQL_SERVICE_PORT
          value: '3306'
